server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Semua route fallback ke index.html
    # biar React Router yang handle
    location / {
        try_files $uri $uri/ /index.html;
    }
}