/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ModelRouteImport } from './routes/model'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as AiManagementRouteImport } from './routes/ai-management'
import { Route as DraftsRouteImport } from './routes/Drafts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderAddRouteImport } from './routes/provider.add'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProductsAddRouteImport } from './routes/products.add'
import { Route as ModelAddRouteImport } from './routes/model.add'
import { Route as ModelIdRouteImport } from './routes/model.$id'
import { Route as ProviderIdEditRouteImport } from './routes/provider.$id.edit'
import { Route as ProductsIdEditRouteImport } from './routes/products.$id.edit'
import { Route as ModelIdEditRouteImport } from './routes/model.$id.edit'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AiManagementRoute = AiManagementRouteImport.update({
  id: '/ai-management',
  path: '/ai-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/Drafts',
  path: '/Drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAddRoute = ProviderAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProviderRoute,
} as any)
const ProductsAddRoute = ProductsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ProductsRoute,
} as any)
const ModelAddRoute = ModelAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ModelRoute,
} as any)
const ModelIdRoute = ModelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ModelRoute,
} as any)
const ProviderIdEditRoute = ProviderIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ProductsRoute,
} as any)
const ModelIdEditRoute = ModelIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ModelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Drafts': typeof DraftsRoute
  '/ai-management': typeof AiManagementRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/model/$id': typeof ModelIdRouteWithChildren
  '/model/add': typeof ModelAddRoute
  '/products/add': typeof ProductsAddRoute
  '/provider/$id': typeof ProviderIdRouteWithChildren
  '/provider/add': typeof ProviderAddRoute
  '/model/$id/edit': typeof ModelIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/provider/$id/edit': typeof ProviderIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Drafts': typeof DraftsRoute
  '/ai-management': typeof AiManagementRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/model/$id': typeof ModelIdRouteWithChildren
  '/model/add': typeof ModelAddRoute
  '/products/add': typeof ProductsAddRoute
  '/provider/$id': typeof ProviderIdRouteWithChildren
  '/provider/add': typeof ProviderAddRoute
  '/model/$id/edit': typeof ModelIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/provider/$id/edit': typeof ProviderIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Drafts': typeof DraftsRoute
  '/ai-management': typeof AiManagementRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/model/$id': typeof ModelIdRouteWithChildren
  '/model/add': typeof ModelAddRoute
  '/products/add': typeof ProductsAddRoute
  '/provider/$id': typeof ProviderIdRouteWithChildren
  '/provider/add': typeof ProviderAddRoute
  '/model/$id/edit': typeof ModelIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/provider/$id/edit': typeof ProviderIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Drafts'
    | '/ai-management'
    | '/generate'
    | '/history'
    | '/invite'
    | '/landing'
    | '/login'
    | '/model'
    | '/products'
    | '/provider'
    | '/register'
    | '/schedule'
    | '/settings'
    | '/sitemap'
    | '/model/$id'
    | '/model/add'
    | '/products/add'
    | '/provider/$id'
    | '/provider/add'
    | '/model/$id/edit'
    | '/products/$id/edit'
    | '/provider/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Drafts'
    | '/ai-management'
    | '/generate'
    | '/history'
    | '/invite'
    | '/landing'
    | '/login'
    | '/model'
    | '/products'
    | '/provider'
    | '/register'
    | '/schedule'
    | '/settings'
    | '/sitemap'
    | '/model/$id'
    | '/model/add'
    | '/products/add'
    | '/provider/$id'
    | '/provider/add'
    | '/model/$id/edit'
    | '/products/$id/edit'
    | '/provider/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/Drafts'
    | '/ai-management'
    | '/generate'
    | '/history'
    | '/invite'
    | '/landing'
    | '/login'
    | '/model'
    | '/products'
    | '/provider'
    | '/register'
    | '/schedule'
    | '/settings'
    | '/sitemap'
    | '/model/$id'
    | '/model/add'
    | '/products/add'
    | '/provider/$id'
    | '/provider/add'
    | '/model/$id/edit'
    | '/products/$id/edit'
    | '/provider/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftsRoute: typeof DraftsRoute
  AiManagementRoute: typeof AiManagementRoute
  GenerateRoute: typeof GenerateRoute
  HistoryRoute: typeof HistoryRoute
  InviteRoute: typeof InviteRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ModelRoute: typeof ModelRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ProviderRoute: typeof ProviderRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SitemapRoute: typeof SitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-management': {
      id: '/ai-management'
      path: '/ai-management'
      fullPath: '/ai-management'
      preLoaderRoute: typeof AiManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Drafts': {
      id: '/Drafts'
      path: '/Drafts'
      fullPath: '/Drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/add': {
      id: '/provider/add'
      path: '/add'
      fullPath: '/provider/add'
      preLoaderRoute: typeof ProviderAddRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/products/add': {
      id: '/products/add'
      path: '/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof ProductsAddRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/model/add': {
      id: '/model/add'
      path: '/add'
      fullPath: '/model/add'
      preLoaderRoute: typeof ModelAddRouteImport
      parentRoute: typeof ModelRoute
    }
    '/model/$id': {
      id: '/model/$id'
      path: '/$id'
      fullPath: '/model/$id'
      preLoaderRoute: typeof ModelIdRouteImport
      parentRoute: typeof ModelRoute
    }
    '/provider/$id/edit': {
      id: '/provider/$id/edit'
      path: '/edit'
      fullPath: '/provider/$id/edit'
      preLoaderRoute: typeof ProviderIdEditRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/products/$id/edit': {
      id: '/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/model/$id/edit': {
      id: '/model/$id/edit'
      path: '/edit'
      fullPath: '/model/$id/edit'
      preLoaderRoute: typeof ModelIdEditRouteImport
      parentRoute: typeof ModelIdRoute
    }
  }
}

interface ModelIdRouteChildren {
  ModelIdEditRoute: typeof ModelIdEditRoute
}

const ModelIdRouteChildren: ModelIdRouteChildren = {
  ModelIdEditRoute: ModelIdEditRoute,
}

const ModelIdRouteWithChildren =
  ModelIdRoute._addFileChildren(ModelIdRouteChildren)

interface ModelRouteChildren {
  ModelIdRoute: typeof ModelIdRouteWithChildren
  ModelAddRoute: typeof ModelAddRoute
}

const ModelRouteChildren: ModelRouteChildren = {
  ModelIdRoute: ModelIdRouteWithChildren,
  ModelAddRoute: ModelAddRoute,
}

const ModelRouteWithChildren = ModelRoute._addFileChildren(ModelRouteChildren)

interface ProductsRouteChildren {
  ProductsAddRoute: typeof ProductsAddRoute
  ProductsIdEditRoute: typeof ProductsIdEditRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsAddRoute: ProductsAddRoute,
  ProductsIdEditRoute: ProductsIdEditRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProviderIdRouteChildren {
  ProviderIdEditRoute: typeof ProviderIdEditRoute
}

const ProviderIdRouteChildren: ProviderIdRouteChildren = {
  ProviderIdEditRoute: ProviderIdEditRoute,
}

const ProviderIdRouteWithChildren = ProviderIdRoute._addFileChildren(
  ProviderIdRouteChildren,
)

interface ProviderRouteChildren {
  ProviderIdRoute: typeof ProviderIdRouteWithChildren
  ProviderAddRoute: typeof ProviderAddRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderIdRoute: ProviderIdRouteWithChildren,
  ProviderAddRoute: ProviderAddRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftsRoute: DraftsRoute,
  AiManagementRoute: AiManagementRoute,
  GenerateRoute: GenerateRoute,
  HistoryRoute: HistoryRoute,
  InviteRoute: InviteRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ModelRoute: ModelRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ProviderRoute: ProviderRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SitemapRoute: SitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
